### ISSUE TITLE
Catastrophic croping / resizing

### ISSUE THREAD

**Issue by l1br3** [webprofusion/apetools#5] opened 2018-01-17 12:42 UTC
Hi all the cropping is not working at all for me. 
I tried with a 2208 * 2208 png.

![screenshot from 2018-01-17 13 40 02](https://user-images.githubusercontent.com/3482025/35043260-3db4402a-fb8c-11e7-8c7e-8f17e6e79710.png)

**Comment by webprofusion-chrisc** [comment] 2018-01-17 14:38
Thanks, this is a dupe of #4 pull requests are welcome!

**Comment by marceloHashzen** [comment] 2018-02-04 19:44
I'm trying to create icon and splashscreen for my app, but all the icons comming totally wrong.
I've made a 1024x1024 image with the logo centered, here's what was generated:
![generated](https://user-images.githubusercontent.com/32581245/35781571-ff698ef6-09d2-11e8-99dc-9553bc80a509.png)

**Comment by webprofusion-chrisc** [comment] 2018-02-04 23:59
Thanks, so there's an issue whereby this is currently only working in Chrome, so I'm guessing this is either Firefox or Safari? It was working fine but I think recent patches changed the behaviour somehow.

**Comment by marceloHashzen** [comment] 2018-02-05 11:19
Hi, sorry for the shortage of information.
I'm using Chrome Version 64.0.3282.140 (Official Build) (64-bit) on MacOS 10.12.6.

**Comment by JulioOrellana** [comment] 2018-02-07 20:19
Yeah, in Safari is bugged too

![screen shot 2018-02-07 at 5 18 38 pm](https://user-images.githubusercontent.com/10372340/35939478-ff8553fc-0c2a-11e8-8d08-09f4e06869bb.png)

**Comment by AliasNick** [comment] 2018-03-27 18:46
I have a similar cropping issue. Completely broken unfortunately.
<img width="1920" alt="screen shot 2018-03-27 at 2 40 28 pm" src="https://user-images.githubusercontent.com/12054707/37987753-13ac69fc-31cd-11e8-9e96-31bd1ee1ae57.png">

Using Firefox 59.0.1 64bit on macOS 10.13.3.

**Comment by webprofusion-chrisc** [comment] 2018-03-28 11:24
Ok, pica library updated and working now, instructions also updated to reflect that we expect to sample the background colour from the top left.

![image](https://user-images.githubusercontent.com/2445502/38026144-8e70a78e-32bd-11e8-8804-dad47b86e47d.png)

**Closed by webprofusion-chrisc** 2018-03-28 11:24 UTC
